# Generated by Django 3.0.3 on 2020-08-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200)),
                ('members', models.TextField()),
                ('password', models.CharField(default='changeme', max_length=20)),
            ],
        ),
    ]
