# Generated by Django 3.0.3 on 2020-08-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('members', models.TextField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
